[package]
name = "flvffywvffy/lsplus"
description = "An easier way to create and manage leaderstats."
license = "MIT"
version = "0.1.3"
authors = ["flvffywvffy <flvffywvffy@gmail.com>"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
